#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                    📦 ESTRUCTURA DOCKER CREADA 📦                     ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ ARCHIVOS CREADOS:"
echo "├── Dockerfile"
echo "│   └── Configura Node.js con multi-stage build"
echo "│"
echo "├── docker-compose.yml"
echo "│   └── Para desarrollo y deployments simples"
echo "│"
echo "├── docker-compose.prod.yml"
echo "│   └── Para producción con Traefik (SSL automático)"
echo "│"
echo "├── .env.example"
echo "│   └── Plantilla de variables (copiar y reemplazar)"
echo "│"
echo "├── .env.local"
echo "│   └── Variables para desarrollo (ya con tus datos)"
echo "│"
echo "├── .dockerignore"
echo "│   └── Archivos a ignorar en imagen Docker"
echo "│"
echo "├── DOCKER.md"
echo "│   └── 📖 GUÍA COMPLETA (leer primero!)"
echo "│"
echo "├── DOCKER-QUICK.md"
echo "│   └── 🚀 GUÍA RÁPIDA para empezar"
echo "│"
echo "├── CONFIG-AVANZADA.md"
echo "│   └── 🔧 Traefik y configuración avanzada"
echo "│"
echo "├── create-store.sh"
echo "│   └── 📱 Script para crear nuevas tiendas (Mac/Linux)"
echo "│"
echo "└── create-store.ps1"
echo "    └── 📱 Script para crear nuevas tiendas (Windows)"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 COMIENZA AQUÍ:"
echo ""
echo "1️⃣  Lee la guía:"
echo "    cat DOCKER-QUICK.md"
echo ""
echo "2️⃣  Prueba localmente:"
echo "    docker-compose up --build"
echo ""
echo "3️⃣  Para crear otra tienda (Mac/Linux):"
echo "    ./create-store.sh 'tienda-nombre' 'dominio.com' '+5491234567890'"
echo ""
echo "4️⃣  En Portainer:"
echo "    - Stack name: tienda-nombre"
echo "    - Copiar docker-compose.yml"
echo "    - Agregar variables de .env.ejemplo"
echo "    - Deploy!"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo "   DOCKER.md           → Guía detallada completa"
echo "   DOCKER-QUICK.md     → Resumen rápido"
echo "   CONFIG-AVANZADA.md  → SSL, Traefik, producción"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
